- name: Add deb vscode repo
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present
  when: ansible_distribution == 'Linux Mint'

- name: Add yum vscode repo
  become: yes
  yum_repository:
    name: vscode
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: yes
    enabled: yes
    description: The repo for visual studio code
  when: ansible_distribution == 'Fedora'

- name: Add zypper vscode repo
  become: yes
  community.general.zypper_repository:
    repo: https://packages.microsoft.com/yumrepos/vscode
    auto_import_keys: yes
    state: present

- name: Install vscode
  become: yes
  package:
    name: code
    state: present
