- name: Install lein for Clojure
  get_url:
    url: https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
    dest: "{{ bin_directory.path }}/lein"
    mode: a+x

- name: Create folder for lein
  file:
    path: ~/.lein
    state: directory

- name: Symbolic link for profiles.clj
  file:
    src: "{{ role_path }}/files/profiles.clj"
    dest: ~/.lein/profiles.clj
    state: link

- name: Download Clojure Tools
  get_url:
    url: https://download.clojure.org/install/linux-install-1.10.3.855.sh
    dest: "{{ tmp_directory.path }}/linux-install-1.10.3.855.sh"
    mode: '0700'
  register: clojure_tools

- name: Install Clojure Tools
  become: yes
  command: "{{ clojure_tools.dest }}"
  args:
    creates: "~/usr/local/bin/clojure"

- name: Clean Clojure Tools install
  file:
    state: absent
    path: "{{ clojure_tools.dest }}"

- name : Create folder for Clojure Tools
  file:
    path: ~/.clojure
    state: directory

- name: Symbolic link for Clojure deps.edn
  file:
    src: "{{ role_path }}/files/deps.edn"
    dest: ~/.clojure/deps.edn
    state: link

- name: Download clj-kondo
  get_url:
    url: https://raw.githubusercontent.com/clj-kondo/clj-kondo/master/script/install-clj-kondo
    dest: "{{ tmp_directory.path }}/install-clj-kondo"
    mode : '0700'
  register: clj_kondo
  

- name: Install clj-kondo
  become: yes
  command: "{{ clj_kondo.dest }}"

- name: Clean clj-kondo install
  file:
    state: absent
    path: "{{ clj_kondo.dest }}" 
