- name: Download Haskell
  get_url:
    url: https://get.haskellstack.org/
    dest: "{{ tmp_directory.path }}/temp_haskell.sh"
    mode: a+x
  register: haskell_install

- name: Install Haskell
  become: yes
  command: "{{ haskell_install.dest }}"
  args:
    creates: /usr/local/bin/haskell

- name: Remove Haskell installer
  file:
    path: "{{ haskell_install.dest }}"
    state: absent
