- name: Install basics for Distribution
  include_tasks: "{{ ansible_distribution }}_development_basics.yml"

- name : Install Mercurial
  become: yes
  package:
    name: mercurial
    state: present

- name: Install jq
  become: yes
  package:
    name: jq
    state: present

- name: Add deb elixir repo
  become: yes
  apt:
    deb: https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
    state: present
  when: ansible_distribution == 'Linux Mint'

- name: Install Erlang
  become: yes
  package:
    name: erlang
    state: present
  when: ansible_distribution == 'Linux Mint'

- name: Install Elixir
  become: yes
  package:
    name: elixir
    state: present
  
