- name: Download nvm
  get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh
    dest: "{{ tmp_directory.path }}/install.sh"
    mode: a+x
  register: nvm_install
  
- name: Install nvm for node
  become: yes
  command: "{{ nvm_install.dest }}"
  args:
    creates: ~/.nvm

- name: Remove nvm installer
  file:
    path: "{{ nvm_install.dest }}"
    state: absent
