- name: Check if bat is installed
  command: dpkg-query -l bat
  ignore_errors: yes
  register: bat_check

- name: Download bat
  get_url:
    url: https://github.com/sharkdp/bat/releases/download/v0.16.0/bat_0.16.0_amd64.deb
    dest: "{{ tmp_directory.path }}/bat_01.16.0_amd64.deb"
  register: bat_package
  when: bat_check.stdout.find('no packages found') != -1

- name: Install bat
  become: yes
  apt:
    deb: "{{ bat_package.dest }}"
    state: present
  when: bat_check.stdout.find('no packages found') != -1

- name: Remove bat package
  become: yes
  file:
    path: "{{ bat_package.dest }}"
    state: absent
  when: bat_check.stdout.find('no packages found') != -1

- name: Download and Extract Exa
  unarchive:
    src: https://github.com/ogham/exa/releases/download/v0.9.0/exa-linux-x86_64-0.9.0.zip
    dest: "{{ bin_directory.path }}"
    remote_src: yes
    creates: "{{ bin_directory.path }}/exa-linux-x86_64"

- name: Symbolic link for exa
  file:
    src: "{{ bin_directory.path }}/exa-linux-x86_64"
    dest: "{{ bin_directory.path }}/exa"
    state: link
