- name: Install Zsh
  become: yes
  package:
    name: zsh
    state: present

- name: Install oh-my-zsh
  become: yes
  command: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  creates: ~/.oh-my-zsh/oh-my-zsh.sh
