- name: Install Curl
  become: yes
  package:
    name: curl
    state: present

- name: Install Zsh
  become: yes
  package:
    name: zsh
    state: present

- name: Install oh-my-zsh
  become: yes
  command: curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
  args:
    creates: "install.sh"
  register: stat_result

- name: Install oh-my-zsh
  become: yes
  command: install.sh
  args:
    creates: "~/.oh-my-zsh/oh-my-zsh.sh"
