- name: Install Zsh
  become: yes
  package:
    name: zsh
    state: present

- name: Download oh-my-zsh
  become: yes
  get_url:
    url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: ~/install.sh
    mode: '0700'
  register: oh_my_install

- name: Symbolic link for .zshrc
  file:
    src: '{{ role_path }}/files/.zshrc'
    dest: ~/.zshrc
    state: link

- name: Symbolic link for .zshenv
  file:
    src: '{{ role_path }}/files/.zshenv'
    dest: ~/.zshenv
    state: link

- name: Install oh-my-zsh
  become: yes
  command: '{{ oh_my_install.dest }}'
  args:
    creates: "~/.oh-my-zsh/oh-my-zsh.sh"

- name: Clean oh-my-zsh install
  file:
    state: absent
    path: '{{ oh_my_install.dest }}'

- name: Symbolic link for my theme
  file:
    src: '{{ role_path }}/files/akira.zsh-theme'
    dest: ~/.oh-my-zsh/themes/akira.zsh-theme
    state: link

