- name: Install Curl
  become: yes
  package:
    name: curl
    state: present

- name: Install Zsh
  become: yes
  package:
    name: zsh
    state: present

- name: Download oh-my-zsh
  become: yes
  get_url:
    url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: ~/install.sh
    mode: '0700'
  register: oh_my_install

- name: Install oh-my-zsh
  become: yes
  command: '{{ oh_my_install.dest }}'
  args:
    creates: "~/.oh-my-zsh/oh-my-zsh.sh"

