version: 2.1

jobs:
  mint:
    docker:
      - image: linuxmintd/mint20-amd64
    steps:
      - checkout
      - run: mint/create_user.sh
      - run:
          name: Full setup
          command: |
            su - akira
            mint/up.sh
      # - run: ./test.sh
  fedora:
    docker:
      - image: jorgegueorguiev/fedora-sudo
    steps:
      - checkout
      - run: fedora/create_user.sh
      - run:
          name: Full setup
          command: |
            su - akira
            fedora/up.sh
      # - run: ./test.sh

workflows:
  version: 2
  mint:
    jobs:
      - mint

  fedora:
    jobs:
      - fedora
