version: 2.1

jobs:
  mint:
    docker:
      - image: linuxmintd/mint19.1-amd64
    steps:
      - checkout
      - run: mint/up.sh
      - run: test.sh
  fedora:
    docker:
      - image: fedora:30
    steps:
      - checkout
      - run: fedora/up.sh
      - run: test.sh

workflows:
  version: 2
  mint:
    jobs:
      - mint

  fedora:
    jobs:
      - fedora
