version: 2.1

jobs:
  mint:
    docker:
      - image: linuxmintd/mint19.3-amd64
    steps:
      - checkout
      - run: mint/up.sh
      # - run: ./test.sh
  fedora:
    docker:
      - image: jorgegueorguiev/fedora-sudo
    steps:
      - checkout
      - run: fedora/up.sh
      # - run: ./test.sh

workflows:
  version: 2
  mint:
    jobs:
      - mint

  fedora:
    jobs:
      - fedora
