- name: Install kdiff3
  become: yes
  package:
    name: kdiff3
    state: present

- name: Distribution based utilities
  include_tasks: "{{ ansible_distribution }}_utilities.yml"

- name: Install Pandoc
  become: yes
  package:
    name: pandoc
    state: present
