- name: Install kdiff3
  become: yes
  package:
    name: kdiff3
    state: present

- name: Distribution based utilities
  include_tasks: "{{ ansible_distribution }}_utilities.yml"

- name: Install Pandoc
  become: yes
  package:
    name: pandoc
    state: present

- name: Install OBS
  become: yes
  package:
    name: obs-studio
    state: present

- name: Download Bitwarden
  get_url:
    url: https://github.com/bitwarden/desktop/releases/download/v1.23.1/Bitwarden-1.23.1-x86_64.AppImage
    dest: "{{ bin_directory.path }}/Bitwarden-1.23.1-x86_64.AppImage"
    mode: a+x

# - name: Install Screen on Mint
#   become: yes
#   apt:
#     deb: https://download.screen.so/desktop-app/linux/4.0.4/screen-desktop_4.0.4_amd64.deb
#     state: present
#   when: ansible_distribution == 'Linux Mint'

# - name: Install Screen on Fedora
#   become: yes
#   dnf:
#     name: https://download.screen.so/desktop-app/linux/4.0.4/screen-desktop-4.0.4-1.x86_64.rpm
#     state: present
#   when: ansible_distribution == 'Fedora'

- name: Download OpenShot
  get_url:
    url: https://github.com/OpenShot/openshot-qt/releases/download/v2.5.1/OpenShot-v2.5.1-x86_64.AppImage
    dest: "{{ bin_directory.path }}/OpenShot-v2.5.1-x86_64.AppImage"
    mode: a+x

- name: Download Zulip
  get_url:
    url: https://github.com/zulip/zulip-desktop/releases/download/v5.5.0/Zulip-5.5.0-x86_64.AppImage
    dest: "{{ bin_directory.path }}/Zulip-5.5.0-x86_64.AppImage"
    mode: a+x

# - name: Install Audacity repo on Mint
#   apt_repository:
#     repo: deb http://ppa.launchpad.net/ubuntuhandbook1/audacity/ubuntu focal main
#   when: ansible_distribution == 'Linux Mint'

# - name: Install Audacity
#   package:
#     name: audacity
#     state: present
