- name: Install kdiff3
  become: yes
  package:
    name: kdiff3
    state: present

- name: Distribution based utilities
  include_tasks: "{{ ansible_distribution }}_utilities.yml"

- name: Install Pandoc
  become: yes
  package:
    name: pandoc
    state: present

- name: Install OBS
  become: yes
  package:
    name: obs-studio
    state: present

- name: Download Bitwarden
  get_url:
    url: https://github.com/bitwarden/desktop/releases/download/v1.18.0/Bitwarden-1.18.0-x86_64.AppImage
    dest: ~/bin/Bitwarden.AppImage
    mode: a+x
