- name: Collect nettools vars
  include_vars:
    file: "{{ role_path }}/vars/{{ ansible_distribution }}.yml"
    name: nettools_vars

- name: Install Curl
  become: yes
  package:
    name: curl
    state: present

- name: Install wget
  become: yes
  package:
    name: wget
    state: present

- name: Install SSL
  become: yes
  package:
    name: "{{ nettools_vars.open_ssl_package_name }}"
    state: present

- name: Install apt transport
  become: yes
  apt:
    name: apt-transport-https
    state: present
  when: ansible_distribution == 'Linux Mint'

- name: Install ca certificates
  become: yes
  apt:
    name: ca-certificates
    state: present
  when: ansible_distribution == 'Linux Mint'
