- name: Create bin directory
  file:
    path: ~/bin
    state: directory
  register: bin_directory

- name: Create code directory
  file:
    path: ~/code
    state: directory
  register: code_directory

- name: Create personal directory
  file:
    path: "{{ code_directory.path }}/personal"
    state: directory

- name: Create external directory
  file:
    path: "{{ code_directory.path }}/externals"
    state: directory

- name: Install Which
  become: yes
  dnf:
    name: which
    state: present
  when: ansible_distribution == 'Fedora'

- name: Create tmp directory
  file:
    path: ~/tmp
    state: directory
  register: tmp_directory

# - name: Install Snap
#   become: yes
#   package:
#     name: snapd
#     state: present
