- name: Create bin directory
  file:
    path: ~/bin
    state: directory

- name: Create code directory
  file:
    path: ~/code
    state: directory

- name: Create personal directory
  file:
    path: ~/code/personal
    state: directory

- name: Create external directory
  file:
    path: ~/code/external
    state: directory

- name: Create codurance directory
  file:
    path: ~/code/codurance
    state: directory

- name: Install Which
  dnf:
    name: which
    state: present
  when: ansible_distribution == 'Fedora'

- name: Create tmp directory
  file:
    path: ~/tmp
    state: directory

- name: Get name of user
  command: whoami
  register: user_name

- name: Install Snap
  package:
    name: snapd
    state: present
