- name: Install TfEnv
  git:
    repo: https://github.com/tfutils/tfenv.git
    dest: ~/.tfenv

- name: Download terragrunt
  get_url:
    url: https://github.com/gruntwork-io/terragrunt/releases/download/v0.23.26/terragrunt_linux_amd64
    dest: "{{ bin_directory.path }}/terragrunt"
    mode: a+x

- name: Download CircleCI cli installer
  get_url:
    url: https://raw.githubusercontent.com/CircleCI-Public/circleci-cli/master/install.sh
    dest: ~/circle_install.sh
    mode: a+x
  register: circle_install

- name: Install CircleCI cli
  shell: "DESTDIR={{ bin_directory.path }} {{ circle_install.dest }}"
  args:
    creates: "{{ bin_directory.path }}/circleci"

- name: Remove CircleCI cli installer
  file:
    path: "{{ circle_install.dest }}"
    state: absent

- name: Install fly for Concourse
  unarchive:
    src: https://github.com/concourse/concourse/releases/download/v6.3.0/fly-6.3.0-linux-amd64.tgz
    dest: "{{ bin_directory.path }}"
    remote_src: yes
    creates: "{{ bin_directory.path }}/fly"
    mode: a+x

