- name: Download AWS cli
  unarchive:
    src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: ~/tmp
    remote_src: yes
    creates: ~/tmp/aws
  register: aws_installer

- name: Install AWS cli
  become: yes
  command: "{{ aws_installer.dest }}/install"

- name: Add Azure on Fedora
  yum_repository:
    name: azure-cli
    baseurl: https://packages.microsoft.com/yumrepos/azure-cli
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: yes
    enables: yes
    description: The repo for Azure cli
  when: ansible_distribution == 'Fedora'
  
